# NumPy Arrays

In [1]:
import numpy as np

## Создание массивов

### Из списков

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Встроенные методы создания массивов

#### arrange

Генерирует массив из целых чисел от минимального до максимального с указанным шагом.

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

#### zeros и ones

Функция zeros генерирует массив указанного размера из нулей.
Функция ones генерирует массив указанного размера из единиц.

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### linspace

Генерирует массив из чисел в указанном диапазоне, в указанном количестве.

In [13]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0, 10, 15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

#### eye

Функция генерирует двумерный массив в виде единичной матрицы

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Случайная генерация массивов - пакет random

#### rand

Генерирует массив из указанной размерности из случайных чисел равномерно распределенных на отрезке [0, 1].

In [16]:
np.random.rand(2)

array([0.78362811, 0.04094162])

In [18]:
np.random.rand(5, 5)

array([[0.97968341, 0.83343178, 0.16791424, 0.34002608, 0.78157215],
       [0.19935073, 0.38320299, 0.64619666, 0.63248488, 0.11251283],
       [0.43632788, 0.96252798, 0.1245794 , 0.00332574, 0.93738705],
       [0.60723274, 0.43545911, 0.28237604, 0.27621554, 0.44850833],
       [0.99194091, 0.02206011, 0.74224392, 0.11495926, 0.07523041]])

#### randn

Функция генерирует массив случайных чисел стандартного нормального распределения.

In [19]:
np.random.randn(2)

array([-0.05061198, -0.72511623])

In [20]:
np.random.randn(5, 5)

array([[-0.07534513, -1.0985041 , -0.15316736,  1.24772535,  1.0540869 ],
       [-1.35837377, -1.31749929,  0.85454111,  0.65477235, -0.15379975],
       [-1.62363908,  0.71996053,  1.38944772,  0.26993673, -0.23041363],
       [-0.0188064 ,  0.07085194,  0.81241203, -0.40194409, -0.06169099],
       [-0.03396916, -0.13433324,  0.67140809,  0.4823326 , -0.03962749]])

#### randint

Функция генерирует массив случайных целых чисел в указанном диапазоне в указанном количестве.

In [21]:
np.random.randint(1, 100)

77

In [22]:
np.random.randint(1, 100, 10)

array([90, 92, 39, 20, 79, 54, 14, 98, 74, 97])

## Свойства и методы массивов

In [23]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr

array([47, 43, 14, 23, 36, 37, 22,  8, 38, 20])

### Reshape

Меняет размерность массива

In [26]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

Функции находят минимум и максимум массива, а также их индексы.

In [27]:
ranarr.max()

47

In [28]:
ranarr.argmax()

0

In [29]:
ranarr.min()

8

In [30]:
ranarr.argmin()

7

### Shape

Размерность массива

In [31]:
arr.shape

(25,)

In [32]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [33]:
arr.reshape(1, 25).shape

(1, 25)

In [34]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [35]:
arr.reshape(25, 1).shape

(25, 1)

### dtype

Тип элементов массива

In [36]:
arr.dtype



dtype('int32')