# Индексирование и выбор элементов массива 

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Выбор элементов с помощью номера в скобках

Получение элемента по индексу

In [3]:
arr[8]

8

Получение списка элементов по диапазону

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

Можно присвоить элементам массива значение по индексу

In [7]:
arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Вернем исходный массив

In [8]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Возьмем часть данных

In [9]:
slice_of_arr = arr[:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

Изменим новый массив

In [10]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

**Внимание!!!**  Исходный массив также поменялся.

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Чтобы избежать подобной ошибки, следует использовать копирование 

In [12]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[:6].copy()
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Индексирование двухмерных массивов (матриц)

In [16]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Индексирование строк

In [17]:
arr_2d[1]

array([20, 25, 30])

Получение элемента по индексу

In [18]:
arr_2d[1][0]

20

In [19]:
arr_2d[1, 0]

20

Кусочек массива

In [20]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

## Интересное индексирование

In [21]:
arr2d = np.zeros((10, 10))
arr_length = arr2d.shape[1]
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Можно выбирать любые строки

In [22]:
arr2d[[2, 4, 6, 8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

Причем, в любом порядке

In [23]:
arr2d[[6, 4, 2, 7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Выбор значений по условию

In [24]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Можно применить условия прямо к массиву

In [25]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

Результат также будет массивом

In [26]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

Этот массив можно применить, как указатель на то, какие элементы выбрать

In [27]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

Можно сразу указать условие

In [28]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
x = 2
arr[arr > x]


array([ 3,  4,  5,  6,  7,  8,  9, 10])